apiVersion: apps/v1
kind: Deployment
metadata:
  name: pydio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pydio
  template:
    metadata:
      labels:
        app: pydio
    spec:
      containers:
      - name: pydio
        image: ghcr.io/pmh-only/pydio
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 800Mi
          limits:
            cpu: 100m
            memory: 800Mi
        env:
        - name: CELLS_SITE_EXTERNAL
          value: https://drive.pmh.codes
        volumeMounts:
        - mountPath: /var/cells
          name: pydio-storage
      volumes:
      - name: pydio-storage
        persistentVolumeClaim:
          claimName: pydio-pvc
