apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ingress
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_intercept_errors on;

      if ($uri ~ "^/$") { 
        set $test A; 
      } 
    
      if ($host !~* minio.pmh.codes) { 
        set $test "${test}B"; 
      }
      
      if ($test = AB) {
        rewrite ^/$ /index.html break;
        error_page 4xx =302 https://pmh.codes;
      }
spec:
  ingressClassName: nginx
  rules:
  - host: "*.pmh.codes"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio-service
            port:
              number: 9000
  - host: minio.pmh.codes
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio-service
            port:
              number: 9001
