apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
type: Opaque
data:
  MINIO_ROOT_USER: eW91c2hhbGxub3RwYXNz # youshallnotpass
  MINIO_ROOT_PASSWORD: eW91c2hhbGxub3RwYXNz # youshallnotpass 
