apiVersion: apps/v1
kind: Deployment
metadata:
  name: mntserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mntserver
  template:
    metadata:
      labels:
        app: mntserver
    spec:
      containers:
      - name: mntserver
        image: ghcr.io/pmh-only/mntserver
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
          limits:
            cpu: 10m
            memory: 100Mi
        env:
        - name: DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: mntserver-secrets
              key: DISCORD_TOKEN
