name: Build images - mntserver
on:
  workflow_dispatch:
  push:
    paths:
      - 'images/mntserver/**'

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout files

      - uses: actions/checkout@v4
        name: Checkout files - source
        with:
          repository: pmh-only/djs-bot-for-my-server
          path: 'images/mntserver/source'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/arm64
          context: images/mntserver
          tags: ghcr.io/pmh-only/mntserver
          cache-from: type=gha
          cache-to: type=gha,mode=max
