name: Build images
on:
  workflow_dispatch:
  push:
    paths:
      - 'images/**'
      - '!images/guessaiword/**'

permissions:
  contents: write
  packages: write

jobs:
  find_targets:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.targets.outputs.targets }}
    steps:
      - uses: actions/checkout@v4
        name: Checkout files
      - id: targets
        run: echo "targets=$(ls images | jq -Rsc 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
  build:
    needs: [find_targets]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ${{fromJSON(needs.find_targets.outputs.targets)}}
    steps:
      - uses: actions/checkout@v4
        name: Checkout files
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/arm64
          context: images/${{ matrix.target }}
          build-args: DISABLE_CACHE=${{ github.event.repository.updated_at }}
          tags: ghcr.io/pmh-only/${{ matrix.target }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
