name: Build images - guessaiword
on:
  workflow_dispatch:
  push:
    paths:
      - 'images/guessaiword/**'

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: arc-runner
    steps:
      - uses: actions/checkout@v4
        name: Checkout files

      - uses: actions/checkout@v4
        name: Checkout files - source
        with:
          repository: pmh-only/guess-ai-word
          path: 'images/guessaiword/source'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: images/guessaiword
          tags: ghcr.io/pmh-only/guessaiword
          cache-from: type=gha
          cache-to: type=gha,mode=max
